# Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

name: mysql
version: "5.7.17"
summary: MySQL Community snap
description: MySQL Snap
  Contains the minimal set of binaries needed for the MySQL server and client.
  This is meant as a way to try out MySQL with Snappy, and is not to be
  considered ready for production environments.
  Before running, the process control interface must be connected with the command
  snap connect mysql-experimental:process-control core:process-control
confinement: strict
grade: devel

apps:
  startup:
    command: startup
    plugs:
      - process-control
      - network
      - network-bind
  server:
    command: start-server
    plugs:
      - process-control
      - network
      - network-bind
  client:
    command: start-client
    plugs:
      - process-control
      - network
      - network-bind
  help:
    command: show-help

parts:
  mysql-server:
    prepare: ./stage_binaries.sh
    build-packages: [libaio-dev, libmecab-dev, libnuma-dev, libncurses5-dev, wget, zlib1g-dev]
    plugin: dump
    source: ./
    organize:
      staging-files/usr: usr/
    snap:
      - usr/lib/mysql/plugin/mysql_no_login.so
      - usr/lib/mysql/plugin/innodb_engine.so
      - usr/lib/mysql/plugin/mypluglib.so
      - usr/lib/mysql/plugin/locking_service.so
      - usr/lib/mysql/plugin/adt_null.so
      - usr/lib/mysql/plugin/rewriter.so
      - usr/lib/mysql/plugin/keyring_udf.so
      - usr/lib/mysql/plugin/libmemcached.so
      - usr/lib/mysql/plugin/auth_socket.so
      - usr/lib/mysql/plugin/validate_password.so
      - usr/lib/mysql/plugin/semisync_slave.so
      - usr/lib/mysql/plugin/semisync_master.so
      - usr/lib/mysql/plugin/keyring_file.so
      - usr/lib/mysql/plugin/mysqlx.so
      - usr/lib/mysql/plugin/version_token.so
      - usr/lib/mysql/plugin/libpluginmecab.so
      - usr/lib/mysql/plugin/group_replication.so
      - usr/sbin/mysqld
      - usr/bin/mysqlpump
      - usr/bin/mysql
      - usr/bin/mysql_ssl_rsa_setup
      - usr/bin/my_print_defaults
      - usr/bin/mysqldump
      - usr/bin/mysql_tzinfo_to_sql
      - usr/bin/mysql_upgrade
      - usr/share/mysql/*
  scripts:
    plugin: dump
    source: ./scripts
    organize:
      show-help: bin/show-help
      start-server: bin/start-server
      start-client: bin/start-client
      startup: bin/startup
